name: Assign Users with Labels

on:
  issues:
    types:
      - labeled

jobs:
  assign_users:
    if: |
      github.event.label.name == 'development' ||
      github.event.label.name == 'bug' ||
      github.event.label.name == 'feature' ||
      startsWith(github.event.label.name, 'L1')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Label-User Mapping & Assign Users
        run: |
          set -o allexport
          source .github/label-users.env
          set +o allexport

          LABEL_NAME="${{ github.event.label.name }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          REPO="${{ github.repository }}"
          GITHUB_TOKEN="${{ secrets.GH_TOKEN }}"

          ASSIGNEES=$(eval echo \$$LABEL_NAME)

          if [ -n "$ASSIGNEES" ]; then
            echo "Assigning $ASSIGNEES to issue #$ISSUE_NUMBER"

            ASSIGNEES_JSON=$(echo $ASSIGNEES | jq -R 'split(",")')

            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/assignees \
                 -d "{\"assignees\": $ASSIGNEES_JSON}"
          else
            echo "No matching assignee found for label: $LABEL_NAME"
          fi
