name: Track Work Duration with Labels

on:
  issues:
    types:
      - opened
      - closed

jobs:
  track_work_duration:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Work Start/Stop Time
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          EVENT_TYPE="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")          
          
          if [ "$EVENT_TYPE" == "opened" ]; then
            MESSAGE="🟢 **Work started: $TIMESTAMP.**"
          elif [ "$EVENT_TYPE" == "closed" ]; then
            MESSAGE="🔴 **Work stopped: $TIMESTAMP.**"
          else
            exit 0
          fi

          echo "Adding comment: $MESSAGE"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
               -d "{\"body\": \"$MESSAGE\"}"
